services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  app:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env.dev
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
    ports:
      - '5000:5000'
  web-client:
    build:
      context: ../web-client
      dockerfile: Dockerfile.local
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: web-client
    restart: unless-stopped
    volumes:
      - ../web-client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - app
    ports:
      - '3000:3000'
